### ISSUE TITLE
Trigger callback with initialState

### ISSUE THREAD

**Issue by robbertvancaem** [hankchizljaw/beedle#14]
## Expected Behavior
When I create a new Store with initialState I would expect my callbacks to be called with that initialState. 

## Actual Behavior
I have to trigger my callback once manually before subscribing a callback to the store

1. Create a new Store with initialState
2. Subscribe a callback to the Store
3. Verify the callback has been called with initialState

## Steps to Reproduce the Problem
1. Create a new Store with initialState
2. Subscribe a callback to the Store
3. Verify the callback has not been called with initialState

Is this something you considered? Is it a good idea? Maybe it's a bad idea? 🤔

**Comment by hankchizljaw** [comment]
Hey there @robbertvancaem,

I'm struggling a bit to grasp what you're asking here, sorry! Can you maybe put a reduced test case together that shows me exactly what you're trying to achieve? 

Thanks!

**Comment by robbertvancaem** [comment]
Hi @hankchizljaw, 

I can imagine it's a bit difficult to imagine what I mean 😂 I created a JSFiddle to illustrate what I mean: https://jsfiddle.net/wbe12q9s/1/ 

You'll see in the example that the text shown is still 'This could be "Hello World"'. I'm creating the store with an initialState that says the message is "Hello World", but because my subscribed function isn't called with initialState, but only after dispatching an action, the initial HTML text is still shown. So if I manually call the callback (uncomment the rule on line 203), it works as I would expect. 

Let me know if this clarifies what I mean and if it makes sense 😄

**Comment by hankchizljaw** [comment]
I think I see what you want to do, but remember, the subscribe will only fire when state changes, because you’re subscribing to changes.

I think you’ll benefit from looking at the source code of the examples in the readme 🙂

**Comment by hankchizljaw** [comment]
Yeh I agree on the single source of truth front. That is literally Beedle’s sole purpose. But, you instantiate the store with your initial state, thus having access to it immediately, so I don’t see a benefit to looping and running every subscription callback at that point. 

It’s also worth noting that these are documented as subscriptions to state changes.
