### ISSUE TITLE
stateChange event fires once for each property in the state due to incorrect object.assign use

### ISSUE THREAD

**Issue by interactiveRob** [hankchizljaw/beedle#18]
I implemented this code as written in 
https://css-tricks.com/build-a-state-management-system-with-vanilla-javascript/

I wanted to comment there, but the thread is closed. 

## Issue
I have say 12 properties in my state, and with each mutation, the whole state object gets replaced, thus the 'stateChange' event is getting fired 12 times. 

## Expected Behavior

Expected console.log output--

store.js:52 ACTION: changePage
     store.js:27 stateChange: currentPage: 1

## Actual Behavior

Actual console.log output-- 
ACTION: setLoadingState
store.js:52 ACTION: changePage
     store.js:27 stateChange: currentPage: 1
     store.js:27 stateChange: currentPage: 1
     store.js:27 stateChange: lastPage: 0
     store.js:27 stateChange: direction: down
     store.js:27 stateChange: isLoading: false
     store.js:27 stateChange: isGated: false
     store.js:27 stateChange: isChallenge: false
     store.js:27 stateChange: isLockedState: true
     store.js:27 stateChange: nickname: 
     store.js:27 stateChange: showWave: false
     store.js:27 stateChange: challengePoints: 0
     store.js:27 stateChange: challengePages: 3,5,7,10

## Steps to Reproduce the Problem

1. Add multiple properties to the state 
2. Subscribe to the 'stateChange' event
3. Use the app in the browser and view console.log output

I can make a PR if we decide this change would be helpful.

Current Implementation
       `self.state = Object.assign(self.state, newState);`

Solution: Start with an empty object for mutating the state. 
     `self.state = Object.assign({}, self.state, newState);`
       `this.setTrap(); // then call a method to re-init the set trap Proxy`

**Comment by andybelldesign** [comment]
Yes I have experience this myself! If you could do a PR, that would be _super_ appreciated, thank you.

**Comment by lospringliu** [comment]
me too, got two notifications for each stateChange
```javascript
const storeInstance = new Store({
    actions,
    mutations,
    initialState
});

storeInstance.subscribe( (state) => console.log(state) )

setInterval( function ()  {
        let new_message = storeInstance.dispatch('saySomething', Math.floor(Math.random() * 10000))
    }
    ,1000)
```
```
{ message: 4242 }
{ message: 4242 }
{ message: 3582 }
{ message: 3582 }
{ message: 1191 }
{ message: 1191 }
{ message: 5213 }
{ message: 5213 }
```

**Comment by lospringliu** [comment]
the mutations return state, I think there is no need to merge states together using Object.assign

**Comment by andybelldesign** [comment]
That’s what the commit method is [already doing](https://github.com/andybelldesign/beedle/blob/master/src/beedle.js#L102).

I think the root of our issue is more in the dispatching of change with the proxy/pub sub pattern.

**Comment by interactiveRob** [comment]
Right! I think @lospringliu was suggesting that we take out the object.asssign and just switch use a standard assignment instead. 

Which off the top of my head is going to look like `self.state = newState;`

This fixes the issue with the set trap Proxy, and does not require the Proxy be re-added.

The problem with Object.assign I think, is that when you have matching keys in the source object and the new object, Object.assign will use a setter on every matching key to update the values from the new object. newState is the whole state object, thus Object.assign triggers the proxy X number of times.  

Is there any case or reason where we should stand up for merging with using Object.assign here?

**Comment by andybelldesign** [comment]
Ah got you! I have no qualms with it being removed. It was very much a lazy implementation on my part :)

**Comment by lospringliu** [comment]
I think it is better to have the attribute as self.store_actual thus make self.store pure proxy, add the get trap too.

this may seems more clear

**Comment by andybelldesign** [comment]
I like where this is going for sure. Are you happy to still do a pr @interactiveRob?

**Comment by Andy-set-studio** [comment]
Just realised this was still open, even after a fix. Closing :)
