### ISSUE TITLE
Update package.json to reflect the license file

### ISSUE THREAD

**Issue by alexcarpenter** [hankchizljaw/beedle#8]
Currently your package.json file is specifying ISC when you license file is supporting MIT.

https://github.com/hankchizljaw/beedle/blob/0077660e125f89d10f47b9095c8961ee31b1c0f3/package.json#L23

**Comment by hankchizljaw** [comment]
Ah, that's what `npm init -y` gets ya 😂 

Good catch @alexcarpenter

**Comment by hankchizljaw** [comment]
Fixed with #9
